### ISSUE TITLE
bootstrap.min.css.map Source Map Error

### ISSUE THREAD

**Issue by Salt54J** [pkp/healthSciences#117]
Hi, I installed this plugin and it seems to be working OK (the theme looks great!), but I noticed on the console that I am getting a source map error when I load the journal homepage.

> Source map error: request failed with status 404
> Resource URL: https://domainname.com/plugins/themes/healthSciences/libs/bootstrap.min.css
> Source Map URL: bootstrap.min.css.map

OJS: 3.1.1.4
Health Sciences Theme: 1.0.2
Hosting: Shared hosting, OJS installed via Softaculous
Permissions: All the files in the theme are permissioned 0644 (all can read, user can write) and folders are 0755 (all can read, user can write, all can execute)
Browser: Firefox 62.0.3 on Windows 10 Pro

Thanks for all of your hard work

**Comment by Vitaliy-1** [comment]
Hi @Salt54J 
Thanks on this one.
This error means that browser can't find the file pointed here: https://github.com/pkp/healthSciences/blob/master/libs/bootstrap.min.css#L7

Source map files, like `bootstrap.min.css.map`, are generated automatically during files minification/compiling process. They actually are not needed for the production, but at the same time occupy 3 times more disk space than ones which they are mapping. That's why I don't include them in the release.

If you want just to remove that message, you can either remove comments like `/*# sourceMappingURL=bootstrap.min.css.map */` in `bootstrap.min.css`, `bootstrap.min.js` and `popper.min.js` or download source map files from a Bootstrap 4.1.3 release and put them inside `libs` directory

**Comment by arvindjugtwan00** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/42616980/92301439-a9fd7080-ef81-11ea-8644-f6dd051b4c98.png)
how to solve below errors

**Comment by Tipsy-Spirit** [comment]
> ![Screenshot (51)](https://user-images.githubusercontent.com/42616980/92301439-a9fd7080-ef81-11ea-8644-f6dd051b4c98.png)
> how to solve below errors

Hi arvindjugtwan00, 
                               Even i got the same error as you have got but it was resolved by deleting few line so you just have to delete 
the line " /*# sourceMappingURL=bootstrap.min.css.map */ " in folder 'styles/bootstrap4/bootstrap.min.css.map'
and the line " //# sourceMappingURL=bootstrap.min.js.map./ " in folder 'styles/bootstrap4/bootstrap.min.css.js'
and the line " //# sourceMappingURL=popper.js.map " in folder 'styles/bootstrap4/popper.js'

that all you have to do !!

**Comment by htcrefactor** [comment]
I was just curious... The lines instructed to delete/comment are comments but why does these lines affect the behavior? They're comments which should have no effect, isn't it?

**Comment by DarkXuX** [comment]
_a_
